enum AppNotificationType {
  newMessage,
  newProposal,
  proposalAccepted,
  proposalRejected,
  jobApproved,
  jobRejected,
  contractCreated,
  workSubmitted,
  contractCompleted,
  newJobPosted,
  walletUpdated,
  coinRefund,
  payoutStatusChanged,
  systemAnnouncement,
}