// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7gKQCF4pCHfYaw-ERXeRDXM3afOmUy_k',
    appId: '1:1032314150639:web:24678c32fc5f0d9fd9c51a',
    messagingSenderId: '1032314150639',
    projectId: 'taskora-55ed3',
    authDomain: 'taskora-55ed3.firebaseapp.com',
    storageBucket: 'taskora-55ed3.firebasestorage.app',
    measurementId: 'G-XTMNTMLCC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANr6eTOMtEXGHLFM36jqB3qAd3XzsOcN4',
    appId: '1:1032314150639:android:db2c21bf5ae125a1d9c51a',
    messagingSenderId: '1032314150639',
    projectId: 'taskora-55ed3',
    storageBucket: 'taskora-55ed3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7gKQCF4pCHfYaw-ERXeRDXM3afOmUy_k',
    appId: '1:1032314150639:web:d19465706e308ad0d9c51a',
    messagingSenderId: '1032314150639',
    projectId: 'taskora-55ed3',
    authDomain: 'taskora-55ed3.firebaseapp.com',
    storageBucket: 'taskora-55ed3.firebasestorage.app',
    measurementId: 'G-E7WDRWPZMQ',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0mscJkcVeSF5BwY_B1oK--zY2snap3c',
    appId: '1:1032314150639:ios:9c9b695e4503e90ed9c51a',
    messagingSenderId: '1032314150639',
    projectId: 'taskora-55ed3',
    storageBucket: 'taskora-55ed3.firebasestorage.app',
    iosBundleId: 'com.mndrs.taskora',
  );
}
