import 'package:flutter/material.dart';

/// SaaS Projesinin Tüm Dinamik Sabitleri ve Çoklu Dil Altyapısı
class AppConstants {
  AppConstants._(); // Nesne üretilmesini engellemek için private constructor

  // --- Şirket & Uygulama Bilgileri ---
  static const String appName = 'Freelance SaaS Platform';
  static const String appVersion = '1.0.0';
  static const String supportEmail = 'support@yourdomain.com';

  // --- Tasarım Sabitleri (Cyberpunk & Kurumsal Dengesi) ---
  static const double defaultPadding = 16.0;
  static const double defaultRadius = 18.0;
  static const double cardRadius = 24.0;

  // --- SaaS Paket Tanımlamaları ---
  static const Map<String, Map<String, dynamic>> subscriptionPlans = {
    'free': {
      'name': 'Free',
      'price': 0,
      'jobLimit': 3,
      'proposalLimit': 10,
    },
    'pro': {
      'name': 'Pro',
      'price': 9.99,
      'jobLimit': 20,
      'proposalLimit': 100,
    },
    'enterprise': {
      'name': 'Enterprise',
      'price': 49.99,
      'jobLimit': 9999,
      'proposalLimit': 9999,
    },
  };

  // --- Çoklu Dil Sözlüğü (Localization Dictionary) ---
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'login': 'Giriş Yap',
      'register': 'Kayıt Ol',
      'welcome_title': 'Hoş Geldiniz',
      'welcome_subtitle': 'Geleceğin çalışma modeline adım atın.',
      'create_job': 'İlan Oluştur',
      'send_proposal': 'Teklif Gönder',
      'settings': 'Ayarlar',
      'logout': 'Çıkış Yap',
      'delete_account': 'Hesabımı Kalıcı Olarak Sil',
      'limit_error_title': 'Limit Sınırına Ulaştınız!',
      'limit_error_desc': 'Mevcut paketinizin limitlerini aşmamak için lütfen planınızı yükseltin.',
      'upgrade_button': 'PRO Plana Geç',
      'error_occurred': 'Bir hata oluştu',
      'success_job': 'İlan başarıyla oluşturuldu.',
      'success_proposal': 'Teklif başarıyla gönderildi.',
      'email': 'E-posta Adresi',
      'password': 'Şifre',
      'first_name': 'Ad',
      'last_name': 'Soyad',
      'role_selection': 'Rol Seçimi',
      'freelancer': 'Freelancer (İş Arayan)',
      'employer': 'İşveren (İlan Veren)',
      'wallet': 'Cüzdan',
      'balance': 'Bakiye',
      'deposit': 'Para Yükle',
      'withdraw': 'Para Çek',
      'contracts': 'Sözleşmeler',
      'no_data': 'Veri bulunamadı.',
    },
    'en': {
      'login': 'Sign In',
      'register': 'Sign Up',
      'welcome_title': 'Welcome',
      'welcome_subtitle': 'Step into the future of work.',
      'create_job': 'Post a Job',
      'send_proposal': 'Submit Proposal',
      'settings': 'Settings',
      'logout': 'Log Out',
      'delete_account': 'Permanently Delete My Account',
      'limit_error_title': 'Limit Reached!',
      'limit_error_desc': 'Please upgrade your plan to bypass current limits.',
      'upgrade_button': 'Upgrade to PRO',
      'error_occurred': 'An error occurred',
      'success_job': 'Job posted successfully.',
      'success_proposal': 'Proposal submitted successfully.',
      'email': 'Email Address',
      'password': 'Password',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'role_selection': 'Select Role',
      'freelancer': 'Freelancer',
      'employer': 'Employer',
      'wallet': 'Wallet',
      'balance': 'Balance',
      'deposit': 'Deposit',
      'withdraw': 'Withdraw',
      'contracts': 'Contracts',
      'no_data': 'No data found.',
    },
    'de': {
      'login': 'Einloggen',
      'register': 'Registrieren',
      'welcome_title': 'Willkommen',
      'welcome_subtitle': 'Treten Sie ein in die Zukunft der Arbeit.',
      'create_job': 'Job posten',
      'send_proposal': 'Vorschlag senden',
      'settings': 'Einstellungen',
      'logout': 'Abmelden',
      'delete_account': 'Konto dauerhaft löschen',
      'limit_error_title': 'Limit erreicht!',
      'limit_error_desc': 'Bitte aktualisieren Sie Ihren Plan, um Limits zu umgehen.',
      'upgrade_button': 'Auf PRO upgraden',
      'error_occurred': 'Ein Fehler ist aufgetreten',
      'success_job': 'Job erfolgreich gepostet.',
      'success_proposal': 'Vorschlag erfolgreich gesendet.',
      'email': 'E-Mail-Adresse',
      'password': 'Passwort',
      'first_name': 'Vorname',
      'last_name': 'Nachname',
      'role_selection': 'Rolle auswählen',
      'freelancer': 'Freelancer',
      'employer': 'Arbeitgeber',
      'wallet': 'Geldbörse',
      'balance': 'Kontostand',
      'deposit': 'Einzahlen',
      'withdraw': 'Auszahlen',
      'contracts': 'Verträge',
      'no_data': 'Keine Daten gefunden.',
    },
    'es': {
      'login': 'Iniciar Sesión',
      'register': 'Registrarse',
      'welcome_title': 'Bienvenido',
      'welcome_subtitle': 'Paso hacia el futuro del trabajo.',
      'create_job': 'Publicar Empleo',
      'send_proposal': 'Enviar Propuesta',
      'settings': 'Configuración',
      'logout': 'Cerrar Sesión',
      'delete_account': 'Eliminar cuenta permanentemente',
      'limit_error_title': '¡Límite alcanzado!',
      'limit_error_desc': 'Por favor, actualice su plan para eludir los límites.',
      'upgrade_button': 'Actualizar a PRO',
      'error_occurred': 'Ha ocurrido un error',
      'success_job': 'Empleo publicado con éxito.',
      'success_proposal': 'Propuesta enviada con éxito.',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'role_selection': 'Seleccionar Rol',
      'freelancer': 'Freelancer',
      'employer': 'Empleador',
      'wallet': 'Billetera',
      'balance': 'Saldo',
      'deposit': 'Depositar',
      'withdraw': 'Retirar',
      'contracts': 'Contratos',
      'no_data': 'No se encontraron datos.',
    },
    'it': {
      'login': 'Accedi',
      'register': 'Registrati',
      'welcome_title': 'Benvenuto',
      'welcome_subtitle': 'Entra nel futuro del lavoro.',
      'create_job': 'Pubblica un Lavoro',
      'send_proposal': 'Invia Proposta',
      'settings': 'Impostazioni',
      'logout': 'Disconnetti',
      'delete_account': 'Elimina l\'account permanentemente',
      'limit_error_title': 'Limite Raggiunto!',
      'limit_error_desc': 'Aggiorna il tuo piano per superare i limiti attuali.',
      'upgrade_button': 'Aggiorna a PRO',
      'error_occurred': 'Si è verificato un errore',
      'success_job': 'Lavoro pubblicato con successo.',
      'success_proposal': 'Proposta inviata con successo.',
      'email': 'Indirizzo E-mail',
      'password': 'Password',
      'first_name': 'Nome',
      'last_name': 'Cognome',
      'role_selection': 'Seleziona Ruolo',
      'freelancer': 'Freelancer',
      'employer': 'Datore di lavoro',
      'wallet': 'Portafoglio',
      'balance': 'Saldo',
      'deposit': 'Deposita',
      'withdraw': 'Preleva',
      'contracts': 'Contratti',
      'no_data': 'Nessun dato trovato.',
    },
    'zh': {
      'login': '登录',
      'register': '注册',
      'welcome_title': '欢迎',
      'welcome_subtitle': '迈向未来的工作模式。',
      'create_job': '发布职位',
      'send_proposal': '提交方案',
      'settings': '设置',
      'logout': '登出',
      'delete_account': '永久删除账户',
      'limit_error_title': '达到限制！',
      'limit_error_desc': '请升级您的计划以绕过当前限制。',
      'upgrade_button': '升级到 PRO',
      'error_occurred': '发生错误',
      'success_job': '职位发布成功。',
      'success_proposal': '方案提交成功。',
      'email': '电子邮箱',
      'password': '密码',
      'first_name': '名字',
      'last_name': '姓氏',
      'role_selection': '选择角色',
      'freelancer': '自由职业者',
      'employer': '雇主',
      'wallet': '钱包',
      'balance': '余额',
      'deposit': '充值',
      'withdraw': '提现',
      'contracts': '合同',
      'no_data': '未找到数据。',
    },
    'ru': {
      'login': 'Войти',
      'register': 'Регистрация',
      'welcome_title': 'Добро пожаловать',
      'welcome_subtitle': 'Шагните в будущее сферы труда.',
      'create_job': 'Разместить заказ',
      'send_proposal': 'Отправить отклик',
      'settings': 'Настройки',
      'logout': 'Выйти',
      'delete_account': 'Удалить аккаунт навсегда',
      'limit_error_title': 'Лимит достигнут!',
      'limit_error_desc': 'Пожалуйста, обновите тарифный план для снятия лимитов.',
      'upgrade_button': 'Перейти на PRO',
      'error_occurred': 'Произошла ошибка',
      'success_job': 'Заказ успешно размещен.',
      'success_proposal': 'Отклик успешно отправлен.',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'role_selection': 'Выбор роли',
      'freelancer': 'Фрилансер',
      'employer': 'Заказчик',
      'wallet': 'Кошелек',
      'balance': 'Баланс',
      'deposit': 'Пополнить',
      'withdraw': 'Вывести',
      'contracts': 'Контракты',
      'no_data': 'Данные не найдены.',
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcome_title': 'مرحباً بك',
      'welcome_subtitle': 'خطوة نحو مستقبل العمل.',
      'create_job': 'نشر وظيفة',
      'send_proposal': 'تقديم عرض',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'delete_account': 'حذف الحساب نهائياً',
      'limit_error_title': 'تم الوصول للحد الأقصى!',
      'limit_error_desc': 'يرجى ترقية خطتك لتجاوز القيود الحالية.',
      'upgrade_button': 'الترقية إلى PRO',
      'error_occurred': 'حدث خطأ ما',
      'success_job': 'تم نشر الوظيفة بنجاح.',
      'success_proposal': 'تم تقديم العرض بنجاح.',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'role_selection': 'اختر الدور',
      'freelancer': 'مستقل',
      'employer': 'صاحب عمل',
      'wallet': 'المحفظة',
      'balance': 'الرصيد',
      'deposit': 'إيداع',
      'withdraw': 'سحب',
      'contracts': 'العقود',
      'no_data': 'لم يتم العثور على بيانات.',
    },
  };

  /// Aktif dile göre kelimenin çevirisini döndürür.
  static String translate(BuildContext context, String key) {
    final locale = Localizations.maybeLocaleOf(context)?.languageCode ?? 'tr';
    final currentDict = _localizedValues[locale] ?? _localizedValues['tr']!;
    return currentDict[key] ?? key;
  }
}